version: '3.9'

services:
    frontend:
        build:
            context: ./front
            dockerfile: ../docker/vue/Dockerfile
        container_name: envybox-frontend
        restart: unless-stopped
        working_dir: /app
        ports:
            - "3008:80"
        env_file:
            - .env
        volumes:
            - ./front/:/app
        depends_on:
            - api
        networks:
           - envybox-http-server-network

    api:
        build:
            context: ./back
            dockerfile: ../docker/php/Dockerfile
        container_name: envybox-api
        restart: unless-stopped
        user: ${UID}:${GID}
        working_dir: /var/www
        env_file:
            - .env
        volumes:
            - ./back/:/var/www
        depends_on:
            - database
        networks:
           - envybox-http-server-network
           - envybox-api-network

    database:
        container_name: envybox-main-database
        image: postgres:16.0-alpine
        restart: unless-stopped
        ports:
            - "5445:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        networks:
            envybox-api-network:
                aliases:
                    - main-database-host

    nginx:
        image: nginx:1.25.2-alpine
        container_name: envybox-http-server
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./back:/var/www
            - ./back/storage/logs/nginx:/var/log/nginx/
            - ./docker/nginx/default.template:/etc/nginx/templates/default.conf.template
        depends_on:
            - api
        networks:
            - envybox-http-server-network

networks:
    envybox-api-network:
    envybox-http-server-network:
